#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwitterSearchApp.Resource", IsApplication=true)]

namespace TwitterSearchApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::TwitterSearchApp.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::TwitterSearchApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010016
			public const int appTheme = 2130771990;
			
			// aapt resource value: 0x7f01001d
			public const int buyButtonAppearance = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int buyButtonHeight = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int buyButtonText = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int buyButtonWidth = 2130771995;
			
			// aapt resource value: 0x7f010007
			public const int cameraBearing = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraTargetLat = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cameraTargetLng = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cameraTilt = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int cameraZoom = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010017
			public const int environment = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int fragmentMode = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int fragmentStyle = 2130771992;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f01000c
			public const int liteMode = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int mapType = 2130771974;
			
			// aapt resource value: 0x7f010020
			public const int maskedWalletDetailsBackground = 2130772000;
			
			// aapt resource value: 0x7f010022
			public const int maskedWalletDetailsButtonBackground = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int maskedWalletDetailsButtonTextAppearance = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int maskedWalletDetailsHeaderTextAppearance = 2130771999;
			
			// aapt resource value: 0x7f010024
			public const int maskedWalletDetailsLogoImageType = 2130772004;
			
			// aapt resource value: 0x7f010023
			public const int maskedWalletDetailsLogoTextColor = 2130772003;
			
			// aapt resource value: 0x7f01001e
			public const int maskedWalletDetailsTextAppearance = 2130771998;
			
			// aapt resource value: 0x7f01000d
			public const int uiCompass = 2130771981;
			
			// aapt resource value: 0x7f010015
			public const int uiMapToolbar = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public const int uiRotateGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int uiScrollGestures = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int uiTiltGestures = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int uiZoomControls = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int uiZoomGestures = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int useViewLifecycle = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int zOrderOnTop = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070009
			public const int common_action_bar_splitter = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int common_signin_btn_dark_text_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_signin_btn_dark_text_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_signin_btn_dark_text_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_signin_btn_dark_text_pressed = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int common_signin_btn_default_background = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int common_signin_btn_light_text_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_signin_btn_light_text_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_signin_btn_light_text_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_signin_btn_light_text_pressed = 2131165189;
			
			// aapt resource value: 0x7f070017
			public const int common_signin_btn_text_dark = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int common_signin_btn_text_light = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public const int wallet_bright_foreground_disabled_holo_light = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int wallet_bright_foreground_holo_dark = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int wallet_bright_foreground_holo_light = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int wallet_dim_foreground_disabled_holo_dark = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int wallet_dim_foreground_holo_dark = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int wallet_dim_foreground_inverse_disabled_holo_dark = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int wallet_dim_foreground_inverse_holo_dark = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int wallet_highlighted_text_holo_dark = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int wallet_highlighted_text_holo_light = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int wallet_hint_foreground_holo_dark = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int wallet_hint_foreground_holo_light = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int wallet_holo_blue_light = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int wallet_link_text_light = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int wallet_primary_text_holo_light = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int wallet_secondary_text_holo_dark = 2131165210;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int hourglass = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_medium_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_small_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_standard_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_tall_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int powered_by_google_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int powered_by_google_light = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090010
			public const int book_now = 2131296272;
			
			// aapt resource value: 0x7f090026
			public const int buttonSearch = 2131296294;
			
			// aapt resource value: 0x7f09000c
			public const int buyButton = 2131296268;
			
			// aapt resource value: 0x7f090011
			public const int buy_now = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int buy_with_google = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int classic = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int donate_with_google = 2131296275;
			
			// aapt resource value: 0x7f090023
			public const int editTextSearchRadius = 2131296291;
			
			// aapt resource value: 0x7f09001d
			public const int editTextSearchText = 2131296285;
			
			// aapt resource value: 0x7f090015
			public const int grayscale = 2131296277;
			
			// aapt resource value: 0x7f090007
			public const int holo_dark = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int holo_light = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int hybrid = 2131296259;
			
			// aapt resource value: 0x7f090024
			public const int imageViewLoading = 2131296292;
			
			// aapt resource value: 0x7f090017
			public const int linearLayout1 = 2131296279;
			
			// aapt resource value: 0x7f090028
			public const int linearLayout13 = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int linearLayout14 = 2131296297;
			
			// aapt resource value: 0x7f090027
			public const int linearLayout2 = 2131296295;
			
			// aapt resource value: 0x7f090018
			public const int linearLayout3 = 2131296280;
			
			// aapt resource value: 0x7f09001a
			public const int linearLayout4 = 2131296282;
			
			// aapt resource value: 0x7f09001e
			public const int linearLayout5 = 2131296286;
			
			// aapt resource value: 0x7f09001b
			public const int linearLayout6 = 2131296283;
			
			// aapt resource value: 0x7f09001f
			public const int linearLayout7 = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int linearLayout8 = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int linearLayout9 = 2131296290;
			
			// aapt resource value: 0x7f09002b
			public const int linearLayoutMap = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int linearLayoutPostAuthor = 2131296301;
			
			// aapt resource value: 0x7f09002a
			public const int listView1 = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int map = 2131296300;
			
			// aapt resource value: 0x7f09000e
			public const int match_parent = 2131296270;
			
			// aapt resource value: 0x7f090016
			public const int monochrome = 2131296278;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int normal = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int production = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int sandbox = 2131296266;
			
			// aapt resource value: 0x7f090005
			public const int satellite = 2131296261;
			
			// aapt resource value: 0x7f09000d
			public const int selectionDetails = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int strict_sandbox = 2131296267;
			
			// aapt resource value: 0x7f090006
			public const int terrain = 2131296262;
			
			// aapt resource value: 0x7f090019
			public const int textView1 = 2131296281;
			
			// aapt resource value: 0x7f09001c
			public const int textView2 = 2131296284;
			
			// aapt resource value: 0x7f090020
			public const int textView3 = 2131296288;
			
			// aapt resource value: 0x7f090025
			public const int textViewLoading = 2131296293;
			
			// aapt resource value: 0x7f09002e
			public const int textViewPostAuthor = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int textViewPostText = 2131296303;
			
			// aapt resource value: 0x7f09000f
			public const int wrap_content = 2131296271;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int tweetlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060024
			public const int ApplicationName = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int Hello = 2131099683;
			
			// aapt resource value: 0x7f060002
			public const int accept = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int common_android_wear_notification_needs_update_text = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int common_android_wear_update_text = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int common_android_wear_update_title = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_enable_button = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_enable_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_enable_title = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_error_notification_requested_by_msg = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_install_button = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_install_text_phone = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_install_text_tablet = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_install_title = 2131099660;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_invalid_account_text = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_invalid_account_title = 2131099673;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_needs_enabling_title = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_network_error_text = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_network_error_title = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_needs_installation_title = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_notification_needs_update_title = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_notification_ticker = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_unknown_issue = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_unsupported_text = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_unsupported_title = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_update_button = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_update_text = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_title = 2131099667;
			
			// aapt resource value: 0x7f060021
			public const int common_open_on_phone = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int common_signin_button_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int common_signin_button_text_long = 2131099680;
			
			// aapt resource value: 0x7f060005
			public const int create_calendar_message = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int create_calendar_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int decline = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int store_picture_message = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int store_picture_title = 2131099648;
			
			// aapt resource value: 0x7f060022
			public const int wallet_buy_button_place_holder = 2131099682;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_IAPTheme = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int WalletFragmentDefaultButtonTextAppearance = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int WalletFragmentDefaultDetailsHeaderTextAppearance = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int WalletFragmentDefaultDetailsTextAppearance = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int WalletFragmentDefaultStyle = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] WalletFragmentOptions = new int[] {
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int WalletFragmentOptions_appTheme = 0;
			
			// aapt resource value: 1
			public const int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public const int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public const int WalletFragmentOptions_fragmentStyle = 2;
			
			public static int[] WalletFragmentStyle = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 3
			public const int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public const int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public const int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public const int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public const int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public const int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public const int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public const int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public const int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public const int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public const int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
